# NumPy 배열의 기초

- Numpy의 배열 조작을 사용하는 예제를 살펴보자
- 이 파트에서 다루는 기본 배열 조작의 범주
    1. 배열 속성 지정
    2. 배열 인덱싱
    3. 배열 슬라이싱
    4. 배열 재구조화
    5. 배열 결합 및 분할

### NumPy 배열 속성 지정
- 몇 가지 유용한 배열 속성 알아보기!

In [3]:
#먼저 1차원, 2차원, 3차원 난수 배열을 정의해 보자
#NumPy 난수 생성기를 사용하며 코드를 실행할 때마다 같은 난수 배열이 생성되도록 시드 값을 설정해보자

import numpy as np
np.random.seed(0) #재현 가능성을 위한 시드 값

x1=np.random.randint(10,size=6) #1차원 배열
x2=np.random.randint(10,size=(3,4)) #2차원 배열
x3=np.random.randint(10,size=(3,4,5)) #3차원 배열

#각 배열은 속성으로 ndim(차원의 개수), shape(각 차원의 크기), size(전체 배열의 크기), dtype(각 요소의 타입)을 가짐

### 배열 인덱싱: 단일 요소에 접근하기

In [11]:
#파이썬의 표준 리스트 인덱싱과 마찬가지로 NumPy의 인덱싱도 []안에 원하는 인덱스를 지정하면 된다
print(x1) #print를 사용하면 array([...])가 생략되어서 출력된다
print(x1[0])
print(x1[4])

[5 0 3 3 7 9]
5
7


In [12]:
#음수 인덱싱도 사용 가능
print(x1[-1])
print(x1[-3])

9
3


In [15]:
#다차원 배열은 콤마로 구분된 인덱스 튜플을 이용한다
print(x2)
print(x2[0,0])
print(x2[2,1])
print(x2[-1,2])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3
6
7


In [16]:
#인덱스 표기법을 사용햐 값을 수정하기
x2[0,0]=12
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [17]:
#NumPy 배열은 고정 타입!! 
#x2에 부동 소수점 값을 넣으면 자동으로 소수점이 잘림
x2[0,0]=3.141592
print(x2)
#Q:NumPy는 가능한 상위 타입을 취하려고 하는거 아니였는가? 다른 값들이 부동 소수점으로 바뀌지 않고 3.14..의 소수점이 잘려 정수값이 되는 이유는 무엇인가?
#A:값을 생성할 때는 상위 타입을 취하지만 한번 생성하면 그 타입을 그대로 유지하려한다!

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


### 배열 슬라이싱:하위 배열에 접근하기
- []를 이용해 개별 요소에 접근할 수 있는 것처럼 :으로 표시되는 **슬라이스** 표기법으로 하위 배열에 접근 가능하다
- x[start:stop:step]
- 이 가운데 하나라도 지정되지 않으면 기본으로 start=0, stop=차원 크기, step=1로 값이 설정된다

In [18]:
#1차원 하위 배열
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
print(x[:5]) #첫 대섯 개 요소
print(x[5:]) #인덱스 5 다음 요소들
print(x[4:7]) #중간 하위 배열
print(x[::2]) #하나 걸러 하나씩의 요소로 구성된 배열
print(x[1::2]) #인덱스 1부터 시작해 하나 걸러 하나씩 요소로 구성된 배열

[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]


In [20]:
#다차원 하위 배열
print(x2)
print(x2[:2,:3]) #두 개의 행, 세 개의 열
print(x2[:3,::2]) #모든 행, 한 열 걸러 하나씩

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[3 5 2]
 [7 6 8]]
[[3 2]
 [7 8]
 [1 7]]


In [21]:
#모두 역으로 변환
x2[::-1,::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]], dtype=int32)

In [22]:
#단일 :으로 된 빈 슬라이스를 사용해 배열의 단일 행이나 열에 접근하기
print(x2[:,0]) #x2의 첫 번째 열
print(x2[0,:]) #x2의 첫 번째 행
print(x2[0]) #행에 접근하는 경우 간단하게 : 생략 가능

[3 7 1]
[3 5 2 4]
[3 5 2 4]


In [24]:
#배열 슬라이스는 파이썬 리스트 슬라이싱과 달리 copy가 아닌 view를 반환한다
print(x2)
x2_sub=x2[:2,:2] #x2에서 2*2 배열 추출함
print(x2_sub)

x2_sub[0,0]=99 #x2_sub를 수정
print(x2_sub)
print(x2) #x2도 수정됨(copy가 아닌 view이기 때문!)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[3 5]
 [7 6]]
[[99  5]
 [ 7  6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [25]:
#배열의 사본 만들기
#copy() 메서드로 가능하다
x2_sub_copy=x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [26]:
#이 하위 배열을 수정해도 원래 배열은 그대로 유지된다
x2_sub_copy[0,0]=3
print(x2_sub_copy)
print(x2)

[[3 5]
 [7 6]]
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### 배열 재구조화

In [ ]:
#reshape() 매서드로 배열의 형상 변경하기
grid=np.arange(1,10).reshape((3,3)) #숫자 1~9까지를 3*3 그리드에 넣기
print(grid) #단, 초기 배열의 규모=변경된 배열의 규모여야함

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
x=np.array([1,2,3])
x.reshape((1,3)) #reshape를 이용한 행 벡터

array([[1, 2, 3]])

In [29]:
#newaxis를 이용한 행 벡터
x[np.newaxis,:]

array([[1, 2, 3]])

In [30]:
#reshape를 이용한 열 벡터
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [31]:
#newaxis를 이용한 열 벡터
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

### 배열 연결 및 분할
- 지금까지는 모두 단열 배열에서 동작했지만 이제부터 여러 배열을 하나로 결합하거나 반대로 하나의 배열을 여러 배열로 쪼개보자

In [32]:
#배열 연결
#np.concatenate는 튜플이나 배열의 리스트를 첫 번째 인수로 취함
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [33]:
#한 번에 두 개 이상의 배열 연결 가능
z=[99,99,99]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [37]:
#2차원 배열에서도 사용 가능
grid=np.array([[1,2,3],
               [4,5,6]])
#첫 번째 축을 따라 연결
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [38]:
#두 번째 축을 따라 연결(0부터 시작하는 인덱스 방식)
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [40]:
#혼합된 차원의 배열로 작업할 때는 np.vstack(수직 스택, vertical stack)과 np.hstack(수평 스택, horizontal stack)함수가 더 명확하다
x=np.array([1,2,3])
grid=np.array([[9,8,7],
               [6,5,4]])

#배열을 수직으로 쌓기
print(np.vstack([x,grid]))

#배열을 수평으로 쌓기
y=np.array([[99],
            [99]])
print(np.hstack([grid,y]))

[[1 2 3]
 [9 8 7]
 [6 5 4]]
[[ 9  8  7 99]
 [ 6  5  4 99]]


In [ ]:
#배열 분할
#분할은 np.split, np.hsplit, np.vsplit 함수로 구현한다
#각 함수에 분할 지점을 알려주는 인덱스 목록을 전달할 수 있다

X=[1,2,3,99,99,3,2,1]
X1, X2, X3=np.split(X,[3,5]) #3번 앞, 5번 앞에서 분할
print(X1,X2,X3)

[1 2 3] [99 99] [3 2 1]


In [5]:
#N개의 분할점은 N+1개의 하위 배열을 만든다
#np.hsplit, np.vsplit은 서로 비슷하다
grid=np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
upper, lower=np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [9]:
left,right=np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
