# NumPy 소개

- 데이터를 숫자로 표현하는 것이 데이터 처리의 기본!
- **Numpy**는 python에서 데이터를 효율적으로 저장 및 처리할 수 있게 해줌.

In [ ]:
#NumPy import하기
import numpy as np
numpy.__version__

'2.3.2'

# 파이썬의 데이터 타입 이해하기

- 파이썬은 변수의 타입을 동적으로 추론하는 **동적 타입 체계**이다.
- C나 자바와 같은 정적 타입 체계는 변수의 타입을 하나하나 지정해줘야한다.
- 파이썬의 동적 타입 체계는 서로 다른 데이터 타입을 리스트에 담을 수 있게 함.

### 파썬의 정수는 정수 이상이다
- 표준 파이썬은 C로 구현되어있다.
- 파이썬 3.6의 단일 정수를 실제로 구성하는 구성 요소는 다음과 같다.
   1. ob_refcnt: 파이썬이 조용히 메모리 할당과 해체를 처리할 수 있게 돕는 참조 횟수
   2. ob_type: 변수 타입을 인코딩
   3. ob_size: 다음 데이터 멤버의 크기를 지정
   4. ob_digit: 파이썬 변수가 나타내는 실제 정숫값을 포함

### 파이썬 리스트는 리스트 이상이다
- 파이썬의 유연성은 리스트 내에 서로 다른 타입의 요소를 담을 수 있게 해준다.
- 그러나 이러한 유연성에는 비용이 따른다. 리스트의 각 항목이 타입 정보와 참조 횟수, 기타 정보가 들어있는 완전한 파이썬 객체이다.
- 모든 변수가 같은 타입이라면 이 정보가 불필요하게 중복되니 고정 타입 배열에 데이터를 저장하는 것이 효율적일 수 있다. Numpy는 이러한 고정 타입 배열을 가능하게 한다.
- NumPy 스타일 배열은 유연성은 부족하나 데이터의 저장과 가공 측면에서는 훨씬 효율적이다.


### 파이썬의 고정 타입 배열
- NumPy의 내장 array 모듈은 단일 타입의 조밀한 배열을 만드는데 사용할 수 있다.
- ndarray 객체는 배열 기반 데이터에 효율적인 저장소를 제공하는 array 객체에 효율적인 연산이 추가된다.

In [16]:
#array 모듈
import array
L=list(range(10))
A=array.array('i', L) #'i'는 내용이 정수임을 가리키는 타입 코드
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 파이썬 리스트에서 배열 만들기

In [17]:
import numpy as np #별칭 np로 NumPy import하기

np.array([1,2,3,4,5]) #정수 배열 만들기

array([1, 2, 3, 4, 5])

In [18]:
#NumPy는 베열의 모든 요소가 같은 타입이여야 함

np.array([1,4,2,3.14]) #타입이 일치하지 않으면 NumPy는 가능한 경우 상위 타입을 취한다(다음은 정수의 상위 타입인 부동 소수점으로 변환된다)

array([1.  , 4.  , 2.  , 3.14])

In [19]:
#배열의 데이터 타입을 설정하려면 dtype 키워드 사용하기
np.array([1,2,3,4],dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [20]:
#NumPy 배열은 명시적으로 다차원이 가능함
np.array([range(i, i+3) for i in [2,4,6]]) 

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### 처음부터 배열 만들기
- 규모가 큰 배열의 경우 Numpy에 내장된 루틴을 사용해 처음부터 배열을 생성하는 것이 더 효율적이다

In [21]:
#0으로 채운 길이가 10인 정수 배열 만들기
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
#1로 채운 3*5 부동 소수점 배열 만들기
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
#3.14로 채운 3*5 배열 만들기
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [24]:
#선형 수열로 채운 배열 만들기
#0에서 시작해 2씩 더해 20까지 채움
#내장 함수 range()와 유사함
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
#0과 1 사이에 일정한 간격을 가진 다섯 개의 값으로 채운 배열 만들기
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
#균등하게 분포된 3*3 배열 만들기
#0과 1 사이의 난수로 채움
np.random.random((3,3))

array([[0.10090178, 0.26513834, 0.73225713],
       [0.35669252, 0.12342799, 0.74414789],
       [0.5407976 , 0.68324731, 0.40503012]])

In [27]:
#정규 분포(평균=0, 표준 편차=1)의 난수로 채운 3*3 배열 만들기
np.random.normal(0,1,(3,3))

array([[ 0.03746744, -0.72520655, -0.12185813],
       [-0.82779917, -0.43928034, -0.17723987],
       [ 1.60179448, -1.2320838 ,  2.14812186]])

In [28]:
#[0,10] 구간의 임의의 정수로 채운 3*3 배열 만들기
np.random.randint(0,10,(3,3))

array([[5, 0, 3],
       [4, 6, 0],
       [4, 7, 3]], dtype=int32)

In [29]:
#3*3 단위 행렬 만들기
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
#세 개의 정수를 가지는 초기화되지 않는 배열 만들기
#값은 해당 메모리 위치에 이미 존재하고 있는 값으로 매움
np.empty(3)

array([1., 1., 1.])

### NumPy 표준 데이터 타입

문자열을 이용해 지정하는 것도 가능(dtype='int16')

| 데이터 타입     | 설명                                                                 |
|----------------|----------------------------------------------------------------------|
| `bool_`        | 1바이트로 저장된 부울 값 (참 또는 거짓)                               |
| `int_`         | 기본 정수 타입 (C long과 같음, 일반적으로 int64 또는 int32)           |
| `intc`         | C int와 동일 (일반적으로 int32 또는 int64)                            |
| `intp`         | 인덱싱에 사용하는 정수 (C ssize_t와 동일, 일반적으로 int32 또는 int64) |
| `int8`         | 1바이트 정수 (-128 ~ 127)                                             |
| `int16`        | 정수 (-32,768 ~ 32,767)                                               |
| `int32`        | 정수 (-2,147,483,648 ~ 2,147,483,647)                                 |
| `int64`        | 정수 (-9,223,372,036,854,775,808 ~ 9,223,372,036,854,775,807)         |
| `uint8`        | 부호 없는 정수 (0 ~ 255)                                              |
| `uint16`       | 부호 없는 정수 (0 ~ 65,535)                                           |
| `uint32`       | 부호 없는 정수 (0 ~ 4,294,967,295)                                    |
| `uint64`       | 부호 없는 정수 (0 ~ 18,446,744,073,709,551,615)                       |
| `float_`       | `float64`의 약칭                                                       |
| `float16`      | 반정밀 부동 소수점: 부호 비트 1, 지수 5비트, 가수 10비트               |
| `float32`      | 단정밀 부동 소수점: 부호 비트 1, 지수 8비트, 가수 23비트               |
| `float64`      | 배정밀 부동 소수점: 부호 비트 1, 지수 11비트, 가수 53비트              |
| `complex_`     | `complex128`의 약칭                                                    |
| `complex64`    | 복소수, 두 개의 32비트 부동 소수점으로 표현                            |
| `complex128`   | 복소수, 두 개의 64비트 부동 소수점으로 표현                            |



