# NumPy 배열 연산: 유니버설 함수
- NumPy의 배열의 연산을 빠르게 만들기 위해선 벡터화 연산을 사용해야 한다
- 이는 유니버설 함수(Ufuncs)를 통해 구현된다

### 루프는 느리다
- 파이썬이 동적인 인터프리터 언어이기에 발생하는 '연산 느림'이라는 문제점을 해결하기 위한 많은 시도가 있었지만 표준 파이썬 엔진의 범위와 대중성을 넘지는 못함

In [ ]:
#값으로 이루어진 배열이 있고 각각의 역수를 계산하는 상황
import numpy as np
np.random.seed(0)

def reverse(value):
    output=np.empty(len(value))
    for i in range(len(value)):
        output[i]=1/value[i]
    return output

value=np.random.randint(1,10,size=5)
a=reverse(value)
print(a) 
#이러한 연산은 큰 입력값을 넣으면 매우 느리다




[0.16666667 1.         0.25       0.25       0.125     ]


In [ ]:
big_array=np.random.randint(1,100,size=1000000)
%timeit reverse(big_array) 

250 ms ± 4.39 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Ufuncs 소개
- NumPy의 벡터화 연산은 속도를 매우 빠르게 함

In [ ]:
print(reverse(value))
print(1.0/value)
#둘은 같은 결과를 산출한다

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [ ]:
%timeit (1.0/big_array) #이는 %timeit reverse(big_array)의 결과보다 백배 가량 빠름

3 ms ± 34.2 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
#이러한 벡터화 연산은 Ufuncs를 통해 구현된다
#유니버설 함수는 매우 유연해서 앞서 봤던 스칼라와 배열 사이의 연산뿐만 아니라 배열 간에 연산도 가능하다
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [7]:
#ufuncs 연산은 다차원 배열에도 동작한다
x=np.arange(9).reshape((3,3))
2**x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

### NumPy 유니버설 함수(Ufuncs)


In [8]:
#배열 산술 연산
x=np.arange(4)
print('x    =', x)
print('x + 5=', x+5)
print('x - 5=', x-5)
print('x * 2=', x*2)
print('x / 2=', x/2)
print('x // 2=',x//2) #몫


x    = [0 1 2 3]
x + 5= [5 6 7 8]
x - 5= [-5 -4 -3 -2]
x * 2= [0 2 4 6]
x / 2= [0.  0.5 1.  1.5]
x // 2= [0 0 1 1]


In [9]:
#음수 만들기, 지수 연산, 나머지 연산
print('-x    =', -x)
print('x**2  =', x**2)
print('x%2   =', x%2)

-x    = [ 0 -1 -2 -3]
x**2  = [0 1 4 9]
x%2   = [0 1 0 1]


In [10]:
#섞어 사용 가능
-(0.5*x+1)**2

array([-1.  , -2.25, -4.  , -6.25])

- 이러한 산술 연산은 편의를 위해 NumPy 내장 함수를 감싼 **래퍼 함수**이다

<표준 NumPy 데이터 타입>
| 연산자 | 대응 ufuncs | 설명 |
| :--- | :--- | :--- |
| + | np.add | 덧셈(예: 1 + 1 = 2) |
| - | np.subtract | 뺄셈(예: 3 - 2 = 1) |
| 단항 연산자 | np.negative | 단항 음수(예: -2) |
| * | np.multiply | 곱셈(예: 2 * 3 = 6) |
| / | np.divide | 나눗셈(예: 3 / 2 = 1.5) |
| // | np.floor_divide | 바닥 나눗셈(예: 3 // 2 = 1) |
| ** | np.power | 지수 연산(예: 2 ** 3 = 8) |
| % | np.mod | 나머지 연산(예: 9 % 4 = 1) |

In [11]:
#절댓값 함수
#NumPy는 파이썬 내장 산술 연산자 뿐 아닌 내장된 절댓값 함수도 이해한다
x=np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

In [12]:
#ufuncs은 복소수 데이터도 처리할 수 있으며, 이 경우 절댓값은 크기를 반환한다
x=np.array([3-4j,4-3j,2+0j,0+1j])
abs(x)

array([5., 5., 2., 1.])

In [ ]:
#삼각함수
theta=np.linspace(0,np.pi,3) #각도 배열 정의
print('theta      = ',theta)
print('sin(theta) = ',np.sin(theta))
print('cos(theta) = ',np.cos(theta))
print('tan(theta) = ',np.tan(theta))
#역삼각 함수 또한 사용 가능-arcsin, arccos, arctan

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [ ]:
#지수와 로그
x=[1,2,3]
print('x    = ',x)
print('e^x  = ',np.exp(x))
print('2^x  = ',np.exp2(x))
print('3^x  = ',np.power(3,x))


x    =  [1, 2, 3]
e^x  =  [ 2.71828183  7.3890561  20.08553692]
2^x  =  [2. 4. 8.]
3^x  =  [ 3  9 27]


In [20]:
#로그도 사용 가능
x=[1,2,4,10]
print('x        = ',x)
print('ln(x)    = ',np.log(x)) #기본 np.log 연산자는 자연로그를 제공한다
print('log2(x)  = ',np.log2(x))
print('log10(x) = ',np.log10(x))

x        =  [1, 2, 4, 10]
ln(x)    =  [0.         0.69314718 1.38629436 2.30258509]
log2(x)  =  [0.         1.         2.         3.32192809]
log10(x) =  [0.         0.30103    0.60205999 1.        ]


In [ ]:
#특화된 유니버설 함수
#쌍곡선 삼각 함수, 비트 연산, 비교 연산자, 라디안을 각도로 변환, 반올림과 나머지 등
from spicy import special #이 모듈을 통해 여러가지 수학적 함수들을 구현할 수 있다
