# 팬시 인덱싱

- 여태까지 살펴본 인덱스 = 간단한 인덱스(예: arr[0]), 슬라이스(예: arr[:5]), 부울 마스크(예: arr[arr > 0])
- 팬시 인덱싱은 단순 인덱싱과 비슷함. 그러나 단일 스칼라 대신 인덱스 배열을 전달함.

## 팬시 인덱싱 알아보기

In [1]:
import numpy as np
rand = np.random.RandomState(42)
x = rand.randint(100,size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [2]:
# 세 개의 다른 요소에 접근하기
[x[3],x[7],x[2]]

[np.int32(71), np.int32(86), np.int32(14)]

In [3]:
# 인덱스의 단일 리스트나 배열을 전달하기
ind = [3,7,2]
x[ind]

array([71, 86, 14], dtype=int32)

In [5]:
# 팬시 인덱싱을 이용하면 결과의 형상이 인덱싱 대상 배열의 형상이 아니라 인덱스 배열의 형상을 반영함
ind = np.array([[3,7],
               [4,5]])
x[ind]

array([[71, 86],
       [60, 20]], dtype=int32)

In [6]:
# 팬시 인덱싱은 여러 차원에도 동작
X = np.arange(12).reshape((3,4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# 표준 인덱싱과 같이 첫 번째 인덱스는 행, 두 번째 인덱스는 열
row = np.array([0,1,2])
col = np.array([2,1,3])
X[row,col]
# 결과값: X[0,2], X[1,1], X[2,3]

array([ 2,  5, 11])

In [8]:
# 팬시 인덱싱에서 인덱스 쌍을 만드는 것은 브로드캐스팅 규칙을 따름
# 인덱스 내의 열 벡터와 행 벡터를 결합하면 2차원 결과를 얻음
X[row[:,np.newaxis],col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

## 결합 인덱싱

In [9]:
# 더 강력한 연산을 위해 팬시 인덱싱을 다른 인덱싱 방식과 결합 가능
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
# 팬시 인덱스 + 단순 인덱스
X[2,[2,0,1]]

array([10,  8,  9])

In [12]:
# 팬시 인덱스 + 슬라이싱
X[1:,[2,0,1]]

array([[ 6,  4,  5],
       [10,  8,  9]])

In [13]:
# 팬시 인덱싱 + 마스킹
mask = np.array([1,0,1,0], dtype=bool)
X[row[:,np.newaxis],mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

## 팬시 인덱싱으로 값 변경하기

In [18]:
# 인덱스 배열이 있고 배열에서 그 인덱스 배열에 해당하는 항목에 특정 값을 설정
x = np.arange(10)
i = np.array([2,1,8,4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


In [19]:
# 할당 유형의 연산자 모두 사용 가능
x[i] -= 10
print(x)

[ 0 89 89  3 89  5  6  7 89  9]


In [22]:
# 이 연산에서 반복되는 인덱스는 예상치 못한 결과를 초래할 수도 있음
x = np.zeros(10)
x[[0,0]] = [4,6]
print(x)
# 이 경우 x[0] = 4가 먼저 할당되고 그다음에 x[0] = 6이 할당되어 x[0]은 6이 되었다

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
i = [2,3,3,4,4,4]
x[i] += 1
x
# 중복되는 경우 누적이 되지 않음

array([6., 0., 1., 1., 1., 0., 0., 0., 0., 0.])

In [24]:
# at() 매서드를 사용하면 의도한 결과를 얻을 수 있음
x=np.zeros(10)
np.add.at(x,i,1)
print(x)

[0. 0. 1. 2. 3. 0. 0. 0. 0. 0.]
