# 비교, 마스크, 부울 로직

- 부울 마스크는 배열 내의 값을 검사하고 조작하는 데 사용함.
- 마스킹은 특정 기준에 따라 배열의 값을 추출하거나 수정, 계산, 조작할 때 사용.

## ufunc으로서의 비교 연산자

- 산술 연산자 = +, -, *, / 등
- 비교 연산자 = <, > 등
- 비교 연산자의 결과는 항상 부울 타입의 배열임. 

In [ ]:
import numpy as np

x = np.array([1,2,3,4,5])
x < 3 # 보다 작음

array([ True,  True, False, False, False])

In [2]:
x > 3 # 보다 큼

array([False, False, False,  True,  True])

In [3]:
x <= 3 # 보다 작거나 같음

array([ True,  True,  True, False, False])

In [4]:
x >= 3 # 보다 크거나 같음

array([False, False,  True,  True,  True])

In [5]:
x != 3 # 같지 않음

array([ True,  True, False,  True,  True])

In [6]:
# 두 배열을 항목별로 비교할 수 있으며 복잡 표현식을 적용할 수도 있음

(2*x) == (x**2)

array([False,  True, False, False, False])

| 연산자 | 대응 ufunc |
|-------|-----------|
| == | np.equal |
| != | np.not_equal |
| < | np.less |
| <= | np.less_equal |
| > | np.greater |
| >= | np.greater_equal |

In [23]:
# 산술 연산자처럼 모든 크기와 형상의 배열에 적용됨.
# 2차원 예제

rng = np.random.RandomState(0)
x = rng.randint(10, size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [8]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

## 부울 배열로 작업하기

In [9]:
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


### 요소 개수 세기

In [10]:
# 6보다 작은 값은 몇 개일까?
np.count_nonzero(x < 6)

np.int64(8)

In [11]:
np.sum(x < 6) # False = 0, True = 1

np.int64(8)

In [12]:
# 각 행에 6보다 작은 값은 몇 개일까?
np.sum(x < 6, axis=1)

array([4, 2, 2])

In [13]:
# 8보다 큰 값이 하나라도 있는가?
np.any(x > 8)

np.True_

In [14]:
# 0보다 작은 값이 하나라도 있는가?
np.any(x < 0)

np.False_

In [15]:
# 모든 값이 10보다 작은가?
np.all(x < 10)

np.True_

In [16]:
# 모든 값이 6과 같은가?
np.all(x == 6)

np.False_

In [17]:
# 각 행의 모든 값이 8보다 작은가?
np.all(x < 8,axis=1)

array([ True, False,  True])

### 부울 연산자

- NumPy는 파이썬의 비트 단위 로직 연산자(&,|,^,~)를 배열의 요소 단위로 동작하는 유니버설 함수로 오버로딩 함.

In [19]:
# 3보다 크고 7보다 작은 값들의 개수
np.sum((x > 3)&(x < 7))

np.int64(2)

In [21]:
# A AND B = NOT(A OR B)
np.sum(~( (x <= 3) | (x >= 7) ))

np.int64(2)

| 연산자 | 대응 ufunc |
|-------|-----------|
| & | np.biwise_and |
| \| | np.biwise_or |
| ^ | np.biwise_xor |
| ~ | np.biwise_not |

## 마스크로서의 부울 배열

- 부울 배열을 마스크로 사용해 데이터 자체의 특정 부분 집합을 선택하기

In [ ]:
# x에서 5보다 작은 배열 내 값들을 모두 구하기
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [25]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [26]:
# 마스킹 연산
x[x < 5]

array([0, 3, 3, 3, 2, 4], dtype=int32)